version: '3'
  
services:
  db:
    image: mysql:5.7
    environment:
       MYSQL_DATABASE: "jwtcore"
       MYSQL_ROOT_PASSWORD: "12346"
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - jwt-core
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  
  backend:
    build: ./api
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api   
    networks:
      - jwt-core
    command: php -S 0.0.0.0:8000 -t /api 

volumes:
  jwt-core-php:

networks:
  jwt-core:
    driver: bridge
